subtitle: Got Tech? Will Hack.
description: A Geek, Coder, Designer, Solutionizer, Blogger, Traveller, Photographer, Developer, Tester, Tech Lover, Tech Hacker & Human. :-)
url: https://blog.karun.me

title: Ramblings of a Coder's Mind
author: Karun Japhet
email: karun@japhet.in

subscribe_rss: /atom.xml
simple_search: https://www.google.com/search
date_format: "ordinal"
time_format: "%H:%M %Z"
timezone: Asia/Kolkata

root: /
permalink: /blog/:year/:month/:day/:title/


plugins: _plugins
sass_dir: _sass
code_dir: downloads/code
category_dir: blog/categories


markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes

highlighter: pygments
paginate_path: "posts/:num"
excerpt_link: "Read on &rarr;"
excerpt_separator: "<!--more-->"
recent_posts: 5
paginate: 10
titlecase: true

default_asides:
  - custom/asides/about.html
  - custom/asides/twitter.html
  - asides/recent_posts.html

github_user: JAnderton
github_repo_count: 3
github_skip_forks: true
github_show_profile_link: true
disqus_show_comment_count: true
twitter_tweet_button: true
disqus_short_name: roacm
twitter_user: javatarz
twitter_widget_id: 660845451051008000
googleplus_user: KarunAB
